Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.define "mgr" do |mgr|
        mgr.vm.hostname = "mgr.dev"
        mgr.vm.network :private_network, ip: "192.168.55.1"
        mgr.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        mgr.vm.network :forwarded_port, guest: 22, host: 5555, auto_correct: true
        mgr.vm.provision  "shell", path: "ansible.sh"
    end
    
    config.vm.define "www1" do |www1|
        www1.vm.box = "ubuntu/trusty64"
        www1.vm.hostname = "www1.dev"
        www1.vm.network :private_network, ip: "192.168.55.89"
        www1.vm.network "forwarded_port", guest: 80, host: "8089"
        www1.vm.provider "" do |vb|
          vb.memory = "256"
        end
    end
    
end